name: test aws s3
on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.aws_access_key_id }}
                  aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
                  aws-region: eu-west-1

            - name: Upload json
              run: |
                  echo "Test Upload" > file.txt
                  aws s3 cp file.txt s3://app-dashboard-tester/release/
